export const geoOptions =[
  { value: "AR", label: "Аргентина (AR)" },
  { value: "AU", label: "Австралия (AU)" },
  { value: "BR", label: "Бразилия (BR)" },
  { value: "CA", label: "Канада (CA)" },
  { value: "CN", label: "Китай (CN)" },
  { value: "DE", label: "Германия (DE)" },
  { value: "ES", label: "Испания (ES)" },
  { value: "FR", label: "Франция (FR)" },
  { value: "GB", label: "Великобритания (GB)" },
  { value: "IN", label: "Индия (IN)" },
  { value: "IT", label: "Италия (IT)" },
  { value: "JP", label: "Япония (JP)" },
  { value: "KR", label: "Южная Корея (KR)" },
  { value: "MX", label: "Мексика (MX)" },
  { value: "NL", label: "Нидерланды (NL)" },
  { value: "PL", label: "Польша (PL)" },
  { value: "RU", label: "Россия (RU)" },
  { value: "US", label: "США (US)" },
  { value: "ZA", label: "Южная Африка (ZA)" }
]